#!/bin/sh

FEED_TITLE="Website"
FEED_AUTHOR="notfirefox"
FEED_UPDATED=$(date -u '+%FT%TZ')
FEED_LINK="https://notfirefox.github.io/"

cat << EOF
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>$FEED_TITLE</title>
  <author>
    <name>$FEED_AUTHOR</name>
  </author>
  <updated>$FEED_UPDATED</updated>
  <link>$FEED_LINK</link>
EOF

for file in content/*.html
do
  [ -f "$file" ] || break
  ENTRY_TITLE=$(grep "<h1>" "$file"    |
                grep -v "$FEED_AUTHOR" |
                sed -e 's/\s*<[^>]*>//g')
  ENTRY_LINK="$FEED_LINK$(basename "$file")"
  ENTRY_ID="urn:uuid:$(uuidgen -sn @url -N "$ENTRY_LINK")"
  ENTRY_UPDATED=$(date -r "$file" '+%FT%TZ')
  ENTRY_SUMMARY="Some text."

cat << EOF
  <entry>
    <title>$ENTRY_TITLE</title>
    <link href="$ENTRY_LINK"/>
    <id>$ENTRY_ID</id>
    <updated>$ENTRY_UPDATED</updated>
    <summary>$ENTRY_SUMMARY</summary>
  </entry>
EOF
done

cat << EOF
</feed>
EOF
